name: Build & publish python package to PyPI

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: '3.10'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip build py_version_from_tag
    - name: Update version
      run: |
        python -m py_version_from_tag
    - name: Build package
      run: |
        python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_TOKEN }}
